version: 2

builds:
  - binary: metro
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/cyrilghali/metro-cli/cmd.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: cyrilghali
    name: metro-cli
